source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JZMultiChoicesCircleButton_Example', :exclusive => true do
  pod "JZMultiChoicesCircleButton", :path => "../"
end

target 'JZMultiChoicesCircleButton_Tests', :exclusive => true do
  pod "JZMultiChoicesCircleButton", :path => "../"

  
end
